### ISSUE TITLE
Syntax error on where clause "ERROR: syntax error at or near "(""

### ISSUE THREAD

**Issue by dusfan** [JPiere/jpiere.plugin.webui.simpleinputwindow#1]
Hi,
After upgrade of Idempiere from 5.1 to 8.2, the _orgAccessSQL_ return the organization access with parentheses, which create an issue on returned SQL when concatenate it with table name, i think they should be a substring on this variable.
line affected  _JPiereSimpleInputWindow,  line 1314, version 8.2_

**Comment by JPiere** [comment]
Hi @dusfan 
Thanks for bug report.
I fixed bug.
It was cause JIRA IDEMPIERE-4254.
If you find other problems, please report them.
